/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

public class Solution {
    public char findTheDifference(String s, String t) {
        char[] tot=(s+t).toCharArray();
        if(tot.length==0) return 0;
        int i=0;
        for(i=tot.length-1;i>0;i--){
            tot[i-1]=(char)((int)tot[i]^(int)tot[i-1]);
        }
        return tot[i];
    }
}
